# Generated by Django 4.1.7 on 2023-03-11 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Наименование')),
                ('description', models.TextField(blank=True, max_length=1700, verbose_name='Описание')),
                ('category', models.CharField(choices=[('PC', 'ПК'), ('NoteBook', 'Ноутбук'), ('SmartPhone', 'Смартфоны')], default='Other', max_length=70, verbose_name='Категория')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Цена')),
                ('remainder', models.IntegerField(verbose_name='Остаток')),
                ('img', models.CharField(max_length=400, verbose_name='Фото')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=65, verbose_name='Имя пользователя')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('address', models.CharField(max_length=80, verbose_name='Адрес')),
                ('count', models.IntegerField(verbose_name='Количество')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания')),
                ('product', models.ManyToManyField(related_name='product', to='webapp.product')),
            ],
        ),
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(verbose_name='Количество')),
                ('product', models.ForeignKey(default='Product', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='products', to='webapp.product', verbose_name='Продукт')),
            ],
        ),
    ]
