# Generated by Django 4.1.7 on 2023-03-12 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_alter_basket_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basket',
            name='count',
        ),
        migrations.AddField(
            model_name='basket',
            name='qty',
            field=models.IntegerField(default=1, verbose_name='Количество'),
        ),
    ]
