# Generated by Django 4.1.7 on 2023-03-13 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_basket_is_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basket',
            name='is_deleted',
        ),
    ]
