# Generated by Django 4.1.7 on 2023-03-14 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_alter_order_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='ordered',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='product',
            field=models.ManyToManyField(related_name='products', to='webapp.basket'),
        ),
    ]
