# Generated by Django 4.1.7 on 2023-03-14 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_basket_ordered_alter_order_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basket',
            name='ordered',
        ),
        migrations.AlterField(
            model_name='order',
            name='product',
            field=models.ManyToManyField(related_name='products', to='webapp.product'),
        ),
    ]
