# Generated by Django 4.1.7 on 2023-03-14 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0012_alter_orderitem_order_alter_orderitem_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='product',
            field=models.ManyToManyField(related_name='products', to='webapp.product'),
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
