# Generated by Django 4.1.7 on 2023-03-14 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0013_alter_order_product_delete_orderitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(verbose_name='Количество')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='webapp.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='webapp.product')),
            ],
        ),
        migrations.RemoveField(
            model_name='order',
            name='product'
        ),
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ManyToManyField(related_name='products', through='webapp.OrderItem', to='webapp.product'),
        ),
    ]
